name: TAYVORIQBedrock
options:
  bundleIdPrefix: com.tayvoriq
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.6.0"
    CURRENT_PROJECT_VERSION: "2"
packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    from: 0.9.20
targets:
  TAYVORIQBedrock:
    type: application
    platform: iOS
    sources:
      - TAYVORIQBedrock
    dependencies:
      - package: ZIPFoundation
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tayvoriq.addonmanager.ios
        PRODUCT_NAME: TAYVORIQBedrock
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: TAYVORIQBedrock/Info.plist
    scheme:
      gatherCoverageData: false
