plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mofinance.guard'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mofinance.guard'
        minSdk 26
        targetSdk 35
        versionCode 100400
        versionName '1.4.0'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}
