plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mofit.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.mofit.app.v311"
        minSdk 26
        targetSdk 35
        versionCode 311
        versionName "3.1.1"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
