plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mofit.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.mofit.v6"
        minSdk 26
        targetSdk 35
        versionCode 600
        versionName "6.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
